services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '8001:5432'
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=db
  server:
    build: ./
    ports:
      - '8000:3000'
    depends_on:
      - postgres
    networks:
      - default
